### ISSUE TITLE
No 'restart' 'muffleWarning' found for borders_download("administrative units", quiet = TRUE)

### ISSUE THREAD

**Issue by voss-m** [kadyb/rgugik#101]
Hey! 
Was just running `borders_download("administrative units", quiet = TRUE)` but I cannot make it pass, I constantly get the No 'restart' 'muffleWarning' error. Any idea if the link underneath is correct?

**Comment by kadyb** [comment]
Thanks for the message! It looks like the data source has changed and the current links are no longer working.

**Comment by voss-m** [comment]
Any idea where I could find the active link?

**Comment by kadyb** [comment]
New link is: https://opendata.geoportal.gov.pl/prg/granice/00_jednostki_administracyjne.zip

Fixed in 3ff689b.

**Comment by voss-m** [comment]
Great, thanks a lot!
