### ISSUE TITLE
pkgdown

### ISSUE THREAD

**Issue by Nowosad** [kadyb/rgugik#15]
@kadyb you need to set publishing to the gh-pages branch -  https://docs.github.com/en/enterprise/2.14/user/articles/configuring-a-publishing-source-for-github-pages

**Comment by Nowosad** [comment]
Also see the error at https://github.com/kadyb/rgugik/runs/990838939?check_suite_focus=true. We need to improve/change examples - now they are downloading extremely large files (we should aim for a few MB at best, not few hundreds..).

**Comment by kadyb** [comment]
> @kadyb you need to set publishing to the gh-pages branch - https://docs.github.com/en/enterprise/2.14/user/articles/configuring-a-publishing-source-for-github-pages

1. I set publishing to the gh-pages.

> Also see the error at https://github.com/kadyb/rgugik/runs/990838939?check_suite_focus=true. We need to improve/change examples - now they are downloading extremely large files (we should aim for a few MB at best, not few hundreds..).

2. I think use `deploy_to_branch(examples = FALSE)` should be fine. This is what we do in the case of `rcmdcheck`.

3. I think `rcmdcheck` and `pkgdown` should be in separate files (scripts).

**Comment by Nowosad** [comment]
Ad2. This is a workaround, not a solution. Why? Because potential users will try to run examples and will end up with large (unnecessary) files on their hard drives. I would suggest trying to think of truly minimal examples.  

Ad3. In my opinion it is fine to have them together (for several reasons). One of them is that you do not want to have new website version for not-working code.

**Comment by kadyb** [comment]
2. We can use data from the smallest counties and voivodeships, but it is still a lot of data, so their size will be large.

3. I think, now it's misleading. We have two different jobs under one name and in the overview you don't know if `rcmdcheck` or `pkgdown` really doesn't work, so I think it would be better to separate them. Further, the code will be tested, so you will know if it works or not.
![](https://i.imgur.com/Tknt8rz.png)
_Now it looks like there is a problem with the code package itself, but in fact only the website is not build._

**Comment by kadyb** [comment]
I split these two jobs into two separate scripts (`rcmdcheck.yml` and `pkgdown.yml`). For this moment, I used `deploy_to_branch(examples = FALSE)` and website is [delivered](https://kadyb.github.io/rgugik/), but that doesn't solve the big data problem in the examples. Also, there is no deploy instruction for `pkgdown` if `rcmdcheck` didn't return any error.

**Comment by Nowosad** [comment]
Regarding the big data files in examples, I would suggest:
1. Updating examples with the smallest data possible.
2. Adding comments to the examples when the output file is large (e.g. >5MB). For example, `# Note: the output file has the size of ...`.

**Comment by kadyb** [comment]
> To fix: Article title "| General Geographic Database | Baza Danych Obiektów Ogólnogeograficznych" is so long on website. Should be "General Geographic Database".

Is it possible to change the title only on the page? I think, the title on the website should be only in English, but in the document we should use the Polish and English title, because the Polish is official and reference. Maybe can it be set in `_pkgdown.yml`?

**Comment by Nowosad** [comment]
> > To fix: Article title "| General Geographic Database | Baza Danych Obiektów Ogólnogeograficznych" is so long on website. Should be "General Geographic Database".
> 
> Is it possible to change the title only on the page? I think, the title on the website should be only in English, but in the document we should use the Polish and English title, because the Polish is official and reference. Maybe can it be set in `_pkgdown.yml`?

Done.
