### ISSUE TITLE
Incorrect character encoding after unzip

### ISSUE THREAD

**Issue by kadyb** [kadyb/rgugik#22]
```r
library("rgugik")
borders_download("administrative units", outdir = "test", unzip = FALSE)
```

> Name
> ------------------------
> Jednostki_ewidencyjne.dbf
> Jednostki_ewidencyjne.prj
> Jednostki_ewidencyjne.shp
> Jednostki_ewidencyjne.shx
> Obręby.dbf
> Obręby.prj
> Obręby.shp
> Obręby.shx
> Państwo.dbf
> Państwo.prj
> Państwo.shp
> Państwo.shx
> Powiaty.dbf
> Powiaty.prj
> Powiaty.shp
> Powiaty.shx
> Województwa.dbf
> Województwa.prj
> Województwa.shp
> Województwa.shx
> Gminy.dbf
> Gminy.prj
> Gminy.shp
> Gminy.shx

After `utils::unzip()` there is:

```r
utils::unzip("test/administrative units.zip", exdir = "data")
list.files("data")
#> [1] "Gminy.dbf"                 "Gminy.prj"                
#> [3] "Gminy.shp"                 "Gminy.shx"                
#> [5] "Jednostki_ewidencyjne.dbf" "Jednostki_ewidencyjne.prj"
#> [7] "Jednostki_ewidencyjne.shp" "Jednostki_ewidencyjne.shx"
#> [9] "Obr©by.dbf"                "Obr©by.prj"               
#> [11] "Obr©by.shp"                "Obr©by.shx"               
#> [13] "Paästwo.dbf"               "Paästwo.prj"              
#> [15] "Paästwo.shp"               "Paästwo.shx"              
#> [17] "Powiaty.dbf"               "Powiaty.prj"              
#> [19] "Powiaty.shp"               "Powiaty.shx"              
#> [21] "Wojew˘dztwa.dbf"           "Wojew˘dztwa.prj"          
#> [23] "Wojew˘dztwa.shp"           "Wojew˘dztwa.shx"      
```

**Comment by kadyb** [comment]
Package [zip](https://cran.r-project.org/web/packages/zip/index.html) is probably the solution, instead of using `utils::zip()`.

**Comment by kadyb** [comment]
I wrote an email to GUGiK and they fixed it upstream by change characters to ASCII in filenames.

**Comment by Nowosad** [comment]
WOW. Awesome achievement.
