### ISSUE TITLE
"check_SHA" should be a function

### ISSUE THREAD

**Issue by kadyb** [kadyb/rgugik#25]
Code block "check_SHA" from `tile_download` should be a separate private function, becuase we can't test it now.

**Comment by kadyb** [comment]
Fixed in 04e9fc0

**Comment by kadyb** [comment]
How to test non-exported function? Now I get:

```r
# TEST PACKAGE (CTRL + SHIFT + T)
checkSHA_fun(refSHA = "X", fileSHA = "X")
#> Error in checkSHA_fun(refSHA = orto$sha1, fileSHA = orto$sha1) : 
#>  could not find function "checkSHA_fun"
#> Calls: test_pkg -> withCallingHandlers -> sys.source2 -> eval -> eval
#> Execution halted
```

```r
rgugik:::checkSHA_fun(refSHA = "X", fileSHA = "X")
#> Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
#>  object 'checkSHA_fun' not found
```

**Comment by Nowosad** [comment]
I cannot reproduce this error - I am getting a different one:

```r
> library(testit)
> test_pkg('rgugik')
Error from eval(exprs[i], envir) 
 Error in tile_download(orto, outdir = tmp) : 
  data frame should come from 'request_orto' 
```

**Comment by kadyb** [comment]
Yeah. I only wanted to test one line. Now I updated test and it will fail with the mentioned error.

**Comment by kadyb** [comment]
Probably a function inside a function cannot be exported (at least I wasn't successful). As a solution, I have extracted the function `checkSHA_fun` in the same file (**tile_download.R**) and it seems to be OK (the private function test works too). See 8221fa8.

**Comment by Nowosad** [comment]
Yep, a function inside another ones is in a different environment, and therefore cannot be exported (at least that is my understanding).
