### ISSUE TITLE
Prerender vignettes

### ISSUE THREAD

**Issue by kadyb** [kadyb/rgugik#29]
Can we prerender vignettes instead of building them with `pkgdown`? [There](https://github.com/kadyb/rgugik/actions/runs/282447730) is the same problem that requests from GitHub are blocked in functions `orto_request` and `DEM_request`.
https://ropensci.org/technotes/2019/12/08/precompute-vignettes/

Second problem is that I added "--no-vignettes" argument to `rcmdcheck`, but [still trying](https://github.com/kadyb/rgugik/actions/runs/282447726) to build vignettes. I also removed "--as-cran" argument but without success.

**Comment by Nowosad** [comment]
Hi - I will take a look at in the next two days.

**Comment by Nowosad** [comment]
https://github.com/kadyb/rgugik/pulls

**Comment by Nowosad** [comment]
https://github.com/kadyb/rgugik/pull/30

**Comment by kadyb** [comment]
Log from `rcmdcheck`:

> * checking files in ‘vignettes’ ... NOTE
> The following directory looks like a leftover from 'knitr':
>   ‘figure’
> * checking running R code from vignettes ... SKIPPED
> * checking re-building of vignette outputs ... SKIPPED

Log from `pkgdown`:

> -- Building articles ----------------------------------------------------------
> Writing 'articles/index.html'
> Reading 'vignettes/articles/geodb_description.Rmd'
> Writing 'articles/articles/geodb_description.html'
> Reading 'vignettes/orthophotomap.Rmd'
> Writing 'articles/orthophotomap.html'
> == DONE ========================================

**Comment by kadyb** [comment]
So, let's try:

1. Revert "--as-cran" argument to `rcmdcheck`
2. Add URL with HTML file to `_pkgdown.yml`
3. I think I should rewrite vignette to `stars`, because `raster` takes a long time to process (~6 min for me with data downloading).
4. _The following directory looks like a leftover from 'knitr': ‘figure’_ - What to do with this?

**Comment by Nowosad** [comment]
Ad4 - try https://github.com/kadyb/rgugik/pull/31

**Comment by kadyb** [comment]
Related https://github.com/r-lib/pkgdown/issues/280

**Comment by kadyb** [comment]
[It works](https://kadyb.github.io/rgugik/articles/orthophotomap.html) but under the figures there are unnecessary captions like "plot of chunk unnamed-chunk-9".

**Comment by Nowosad** [comment]
I will try to make it work tomorrow.

**Comment by Nowosad** [comment]
https://github.com/kadyb/rgugik/pull/32

**Comment by kadyb** [comment]
Now we use `stars` instead of `raster` - rasters processing is immediate (use `proxy`).

**Comment by kadyb** [comment]
I suppose if we apply to CRAN, we will have to change vignettes to articles (so they won't generated by CRAN). It only takes to change the location of the files.

**Comment by Nowosad** [comment]
Why? Cannot we just submit as it is? (CRAN will only regerate .Rmd files which do not download anything)

**Comment by kadyb** [comment]
If so, OK. I thought we had to use source .Rmd files that are fully executable (with data downloading).

**Comment by Nowosad** [comment]
Nope. The whole idea now is to knit the `.Rmd.orig` file locally (before submitting to CRAN), which creates a new `.Rmd` file. This new file contains all data downloading results (nothing it being downloaded there).

**Comment by kadyb** [comment]
Next issues:
1. I think this step in `PRECOMPILE.R` is unnecessary because we are building vignettes in pkgdown on GitHub Actions:
```r
library(devtools)
build_vignettes()
```
Right?

2. Maybe before `knit("vignettes/orthophotomap.Rmd.orig", "vignettes/orthophotomap.Rmd")` we should use `setwd()` to save images in the same folder? This is not recommended, but we can try. [More info](https://rdrr.io/github/yihui/knitr/man/knit.html#heading-5).

3. Also, we can try remove "--no-vignettes" argument from `rcmdcheck` and we'll see if it really works.

**Comment by Nowosad** [comment]
1. Yep,  you are probably right.
2. I already tried `opts_knit$set(root.dir = "vignettes/"`, but without any success.
3. Fine by me.

**Comment by kadyb** [comment]
It seems to be working fine.

```r
setwd("vignettes/")
knit("orthophotomap.Rmd.orig", "orthophotomap.Rmd")
```
