### ISSUE TITLE
raster issues in stars

### ISSUE THREAD

**Issue by kadyb** [kadyb/rgugik#33]
1. How to plot two images at once from one stack? I tried:
```r
DTM = read_stars("data/73044_917579_N-33-130-D-b-1-1.asc", proxy = FALSE)
DSM = read_stars("data/73043_917495_N-33-130-D-b-1-1.asc", proxy = FALSE)
DEM = c(DTM, DSM)
plot(DEM)
```
but without a success.

2. Why does the raster appear polynomial smoothed despite the argument `downsample = 0`? It's completely blurry.
```r
plot(DEM, downsample = 0)
```
Change method in colorscale breaks didn't help.

Code in 26fac50

**Comment by Nowosad** [comment]
https://github.com/kadyb/rgugik/commit/72fe8ee56b0fd8529a03d4e6bddb2f289787dab2 (maybe there is a better way to do it, but I usually use tmap for viz purposes)

**Comment by kadyb** [comment]
What about plotting two layers in one figure? I haven't used **stars** before, but it is [possible](https://r-spatial.github.io/stars/articles/stars1.html#reading-a-satellite-image).
Now, in our example we have: `stars object with 2 dimensions and 2 attributes`, in **stars** example it is: `stars object with 3 dimensions (X, Y and 6 bands) and 1 attribute`.

In **raster** this is a simple operation:
```r
DTM = raster("data/73044_917579_N-33-130-D-b-1-1.asc")
DSM = raster("data/73043_917495_N-33-130-D-b-1-1.asc")
DEM = brick(DTM, DSM)
plot(DEM)
# two plots in one figure
```

**Comment by kadyb** [comment]
`st_set_dimensions`?

**Comment by Nowosad** [comment]
https://github.com/Nowosad/geostat_book/blob/ff70660b0e4f2f90e848d58d67fb983769ee858c/08-estymacje.Rmd#L234

```r
DEM = st_redimension(DEM)
```

**Comment by kadyb** [comment]
```r
DEM = merge(DEM)
```
works too.

**Comment by kadyb** [comment]
Do you know how to return values from stars objects as vector? In raster is `getValues`.

```r
pts_matrix = matrix(c(357121.7, 515765.5,
                      357321.2, 516017.9),
                    ncol = 2, byrow = TRUE)
line = st_sfc(st_linestring(pts_matrix), crs = 2180)

# intersect line with DTM (1)
DEM[line][, , , 1]
# it returns stars object
```

The documentation says to use `[[]]`, but not any combination works for me.

**Comment by Nowosad** [comment]
How about:

```r
DEM2 = DEM[line]
c(DEM2$DEM)
```

? (I have not tested it)

**Comment by kadyb** [comment]
```r
DEM2 = DEM[line]
DEM2 = c(DEM2$DTM.DSM)
#> 101200 values
```

```r
as.vector(DEM[, , , 1]$DTM.DSM)
#> 641601 values
```

```r
as.vector(DEM[line][, , , 1]$DTM.DSM)
#> 50600 values
```

```r
st_length(line)
#> 321.7235 [m]
```

In fact, we should get around 321 values, but none of the examples above are equal.

**Comment by Nowosad** [comment]
What is your goal here?  To extract the values along the line? If so, then you should try some other functions, e.g. `st_extract()`...

**Comment by kadyb** [comment]
Exactly. I will try.

**Comment by kadyb** [comment]
No sucess
```r
pts_matrix = matrix(c(357121.7, 515765.5,
                      357321.2, 516017.9),
                    ncol = 2, byrow = TRUE)
line = st_sfc(st_linestring(pts_matrix), crs = 2180)
line = st_line_sample(line, density = 1)
st_extract(DEM, line2)
#> 0 0
```
but the number of points from the line is correct

**Comment by Nowosad** [comment]
It is correct - because you just have two points on the line (start and end).

**Comment by kadyb** [comment]
I think this line consists of 322 points, so I should get 322 values with the elevations, but I get 0. This is definitely not correct.
```r
lengths(line)
[1] 644
```

**Comment by Nowosad** [comment]
How about:

```r
st_extract(DEM, st_cast(line, "MULTIPOINT"))
```

?

**Comment by kadyb** [comment]
`st_extract(DEM, st_cast(line, "POINT"))` does the job, but it seems slow to me.

**Comment by Nowosad** [comment]
`st_extract()` is slow in the current CRAN version (and a bit faster in the dev version).
