### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by kadyb** [kadyb/rgugik#39]
@Nowosad 
1. Could you check [CONTRIBUTING](https://github.com/kadyb/rgugik/blob/master/CONTRIBUTING.md)? What do you think?
2. In README we have:

> Head Office of Geodesy and Cartography in Poland is the main source of the data.
> The main source of spatial data in Poland is the Geoportal.

This is duplicate. Maybe the second sentence should be changed to: "The main service of spatial data in Poland is the Geoportal."?

**Comment by Nowosad** [comment]
1. I will read CONTRIBUTING later today.
2. My suggestion:
> Head Office of Geodesy and Cartography in Poland is the main source of the provided data. All dataset can be explored interactively using the [Geoportal](https://mapy.geoportal.gov.pl/).

**Comment by Nowosad** [comment]
https://github.com/kadyb/rgugik/pull/40
