### ISSUE TITLE
Proposal for `orto_request`

### ISSUE THREAD

**Issue by BERENZ** [kadyb/rgugik#44]
I see that `orto_requests` works also for other geometry types such as points:

```
> point = geocodePL_get(address = "Poznań, Niepodległości 10") 
> point
Simple feature collection with 1 feature and 15 fields
geometry type:  POINT
dimension:      XY
bbox:           xmin: 358437.7 ymin: 506513.4 xmax: 358437.7 ymax: 506513.4
CRS:            EPSG:2180
    city citypart         street number  teryt    simc  ulic   code                            jednostka           x                y accuracy
1 Poznań       NA Niepodległości     10 306401 0969400 14199 61-875 {Polska,wielkopolskie,Poznań,Poznań} 358437.7386 506513.386399999        1
  city_accuracy street_accuracy id              geometry_wkt
1             1               1  1 POINT (358437.7 506513.4)
```

```
> mm = orto_request(point)
> str(mm,1)
'data.frame':	16 obs. of  11 variables:
 $ sheetID    : chr  "N-33-130-D-d-1-2" "N-33-130-D-d-1-2" "N-33-130-D-d-1-2" "N-33-130-D-d-1-2" ...
 $ year       : int  2001 2007 2011 2011 2012 2012 2017 2017 2017 2014 ...
 $ resolution : num  1 0.5 0.25 0.25 0.1 0.1 0.25 0.25 0.25 0.25 ...
 $ composition: Factor w/ 2 levels "CIR","RGB": 2 2 1 2 2 2 1 2 2 2 ...
 $ sensor     : Factor w/ 3 levels "Satellite","Analog",..: 1 2 3 3 3 3 3 3 3 3 ...
 $ CRS        : Factor w/ 2 levels "PL-1992","PL-2000:S6": 1 1 1 1 1 2 1 1 2 1 ...
 $ isFilled   : logi  TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ URL        : chr  "https://opendata.geoportal.gov.pl/ortofotomapa/41/41_3783_N-33-130-D-d-1-2.tif" "https://opendata.geoportal.gov.pl/ortofotomapa/45/45_68512_N-33-130-D-d-1-2.tif" "https://opendata.geoportal.gov.pl/ortofotomapa/69749/69749_128840_N-33-130-D-d-1-2.tif" "https://opendata.geoportal.gov.pl/ortofotomapa/69750/69750_140037_N-33-130-D-d-1-2.tif" ...
 $ seriesID   : int  41 45 69749 69750 229 64923 69883 69884 66266 70086 ...
 $ sha1       : chr  "5919b2efdd677fbca7741ef2e871d3f00e356617" "eae0423c7401e7162de96e260d9830883e0be738" "c9f51d8b240e2a2e8cbf1f2f3b932640bcf6e8c1" "5b29fbefba89a04566e4fb8dacf9a2a11e5193b6" ...
 $ filename   : chr  "41_3783_N-33-130-D-d-1-2" "45_68512_N-33-130-D-d-1-2" "69749_128840_N-33-130-D-d-1-2" "69750_140037_N-33-130-D-d-1-2" ...
```

So I may propose a PR to update the documentation for `orto_request` function?

**Comment by kadyb** [comment]
In fact, we only handle bounding boxes of geometries. For this moment, we didn't support points or lines. There is issues for this: https://github.com/kadyb/rgugik/issues/9.
The reason is that there is no documentation for this service and I don't know what the input should look like. Work is required here, and it has to be done by trial and error approach.

**Comment by kadyb** [comment]
But maybe the current approach is enough for the user?
On the other hand, what about complex geometries like multipoints?

**Comment by BERENZ** [comment]
But actually the example above shows that `orto_requests` works correctly for the `geometry type:  POINT` because of using `st_bbox` (I checked the aerial photos). Documentation suggests that it works only for `geometry type:  POLYGON` or am I mistaken?

**Comment by BERENZ** [comment]
Additionally, I see that if you have multiple objects (eg. `POLYGON`, `POINT`) then the `data.frame` that is returned does not inform to which `POLYGON` or `POINT` it refers to.  It is just a collection of all ortophotomaps found for given place.

**Comment by kadyb** [comment]
Yeah, this function iterates over geometries (it doesn't matter if it is a point, line or polygon), creates bounding box, send request, combines all results and removes duplicates at the end. This is hacky solution. It returns a much larger area and sends n requests.

The best solution would be support for explicit geometries, such as point, line, polygon. Then one request for many points would be enough and the spatial extent would be the same as input.

Technically, we can change the documentation (polygon -> geometry), but I don't know if it will be misleading. There is still the open question for multigeometries.

CC @Nowosad

**Comment by Nowosad** [comment]
@kadyb correct me if I am wrong:

1. The current documentation states that the `orto_request()` excepts only polygons.
2. The actual function, however, takes bounding boxes from given sf objects, and send requests based on the calculated bounding boxes. For example, if we have one polygon - then we have one bounding box, if we have two polygons - we have two bounding boxes, if we have one multipolygon - we have one bounding box, if we have one multipoint - we have one bounding box.

If the above is true - I would suggest changing the name of the first argument to e.g., `x` and updating the documentation to something like:

"x - an sf object with one or more features. Requests are based on the bounding boxes of the provided features."

Also, please update the package version in DESCRIPTION.

(Great work on the recent PR, @BERENZ and @kadyb !)

**Comment by kadyb** [comment]
Yeah, generally it is true. 

> if we have one multipolygon - we have one bounding box, if we have one multipoint - we have one bounding box

Probably yes, but I haven't tested this case.

OK, we can change the documentation in the way Jakub proposes. The same applies to the `DEM_request` function.
Remember to correct the names of the objects in the function (polygon -> obj_geom or something).

**Comment by BERENZ** [comment]
Should I take this? If yes, please assign me to this issue.
