### ISSUE TITLE
Tests fail after testthat update

### ISSUE THREAD

**Issue by kadyb** [kadyb/rgugik#45]
1.
> ── ERROR (test-emuia_download.R:19:1): (code run outside of `test_that()`) ─────
> Error: Error: arguments imply differing number of rows: 0, 1
> Backtrace:
>  1. └─rgugik::emuia_download(TERYT = 2412032, outdir = tmp, unzip = TRUE) test-emuia_download.R:19:0
>  2. └─base::cbind(df_names, URL = URLs)
>  3. └─base::cbind(deparse.level, ...)
>  4. └─base::data.frame(..., check.names = FALSE)

2.
> ── Warning (test-minmaxDTM_get.R:23:1): (code run outside of `test_that()`) ────
> input EPSG must be 2180, trying to transform

**testthat** changelog: https://cran.rstudio.com/web/packages/testthat/news/news.html

**Comment by Nowosad** [comment]
@kadyb the error is due to a inconsistency in the code, and probably not related to the testthat update. In some lines, you are trying to get a vector from a data.frame using df[, "NAME"]. However, it does not work when your data.frame is also of class tibble. Probably better approach is to use df[["NAME"]]. I will update the code soon.

**Comment by Nowosad** [comment]
https://github.com/kadyb/rgugik/commit/60a74302c9b828dcec61e09165b38be1dc4162ee

**Comment by kadyb** [comment]
Thanks. I don't know why, but the warning from **test-minmaxDTM_get.R** is gone too.

**Comment by kadyb** [comment]
There's still a warning in local testing, it doesnt appear on the GitHub.

Try:
```r
minmax_4326 = suppressWarnings(minmaxDTM_get(polygon_4326))
```

BTW: There is a wrong test name "*check if ouput is sf/data.frame*". Should be "*check if results are equal*".
```r
test_that("check if ouput is sf/data.frame", {
  expect_equal(minmax, minmax_4326)
})
```

**Comment by Nowosad** [comment]
@kadyb - I updated all of my packages and checked the tests of **rgugik**. Instead of using `suppressWarnings`, I added a new test. Plus I fixed the wrong test name. I will push my changes soon.

**Comment by Nowosad** [comment]
https://github.com/kadyb/rgugik/commit/14d8481afaf8e80c320205f20f1eace7a1337e33

**Comment by kadyb** [comment]
9d5808d

> == Results =================
> [ FAIL 0 | WARN 0 | SKIP 0 | PASS 69 ]
