### ISSUE TITLE
Error in `geocodePL_get`

### ISSUE THREAD

**Issue by kadyb** [kadyb/rgugik#48]
```r
geocodePL_get(address = "Zalesie")
```

> Error in (function (..., deparse.level = 1, make.row.names = TRUE, stringsAsFactors = default.stringsAsFactors(),  : 
>   invalid list argument: all variables should have the same length

Related comment: https://github.com/kadyb/rgugik/pull/43#issuecomment-719910296

CC @BERENZ

**Comment by BERENZ** [comment]
Ok, I'll take care about that in upcoming days.

**Comment by Nowosad** [comment]
You've been assigned;)
