### ISSUE TITLE
spelling of orto_request()

### ISSUE THREAD

**Issue by adamhsparks** [kadyb/rgugik#57]
Did you mean to leave the "h" out? `ortho_request()` seems more logical to me than `orto_request()` for the spelling of the function given that it's getting orthoimages from the server.

**Comment by kadyb** [comment]
Thanks for bringing this issue up! At the very beginning this function was called only `orto` (from Polish *ortofotomapa* without "h"),  but with the development and creation of the package there was an idea to address it to foreign users, but the function name remained unchanged.
Currently I think it will be a good time to fix it. I will leave the old function name as an alias for compatibility.

**Comment by adamhsparks** [comment]
Makes sense.
