### ISSUE TITLE
Link to cran page/vignettes

### ISSUE THREAD

**Issue by mikerspencer** [kadyb/rgugik#63]
Consider adding a link in the `readme` to the project cran page, or adding links to the vignettes. Many folk are introduced to a package through a vignette, so raising their profile/visibility will help increase your package uptake.

Submitted as part of JOSS review: https://github.com/openjournals/joss-reviews/issues/2948.

**Comment by kadyb** [comment]
Thanks! This is a really great idea. I also think the vignettes will be very helpful to novice users so I will add them to the README.

BTW: The CRAN website can be accessed by clicking on the CRAN badge in [README](https://github.com/kadyb/rgugik/blob/master/README.md).

**Comment by kadyb** [comment]
I fixed this in 04bdc32, but there is a problem with installing **textshaping** package from source (https://github.com/kadyb/rgugik/actions/runs/596692037). It should resolve itself in a few days. I will leave this issue open for now.

**Comment by kadyb** [comment]
It's fine now.
