### ISSUE TITLE
vignette plotting error

### ISSUE THREAD

**Issue by mikerspencer** [kadyb/rgugik#69]
The DEM vignette (https://github.com/kadyb/rgugik/blob/master/vignettes/DEM.Rmd) has a bug in the plotting at line 311. The plotting space retains settings from the DEM plots and needs `dev.off()`, or similar, to reset defaults.

Part of JOSS review: https://github.com/openjournals/joss-reviews/issues/2948

**Comment by mikerspencer** [comment]
Also affects Topo vignette (https://github.com/kadyb/rgugik/blob/master/vignettes/topodb.Rmd) at line 248. Likely a problem with the way the legend is plotted (i.e. subsequent plots appear in the legend space).

**Comment by kadyb** [comment]
Thanks! We generate vignettes from Rmarkdown files in which each figure is plotted in a separate chunk (in a new graphic device), so we didn't encounter a bug with incorrect plotting. Just as you suggested, `dev.off()` resolves the error for R scripts. I added such a note as a comment in https://github.com/kadyb/rgugik/pull/71.
