### ISSUE TITLE
Road to CRAN

### ISSUE THREAD

**Issue by kadyb** [kadyb/rgugik#7]
- [x] Note 1:

> Found the following (possibly) invalid URLs:
>   URL: https://orcid.org/0000-0000-0000-0000
>     From: man/rgugik-package.Rd
>     Status: 404
>     Message: Not Found

- [x] Note 2:

> DESCRIPTION fields with placeholder content:
>   Description: more about what it does (maybe more than one line) use
>     four spaces when indenting paragraphs within the description.

- [x] Warning 1 (@Nowosad):

>   NB: this package now depends on R (>= 3.5.0)
>   WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: ‘rgugik/data/TERYT_county.rda’

This comes from the `save(version = 3)` function. Version 3 is supported from R 3.5.0. This can be changed to version 2 which supports earlier R versions.

- [x] Note 3:

> Files ‘README.md’ or ‘NEWS.md’ cannot be checked without ‘pandoc’ being installed.

- [x] Warning 2:

> Found the following file with non-ASCII characters:
>   voivodeships_names.R
> Portable packages must use only ASCII characters in their R code,
> except perhaps in comments.
> Use \uxxxx escapes for other characters.

- [x] Warning 3:

> Undocumented code objects:
>   ‘TERYT_county’
> Undocumented data sets:
>   ‘TERYT_county’
> All user-level objects in a package should have documentation entries.

- [x] Critical:

> "Packages which use Internet resources should fail gracefully with an informative message if the resource is not available (and not give a check warning nor error)."

**Comment by Nowosad** [comment]
I updated description with new depends and updated description text - dhttps://github.com/kadyb/rgugik/commit/7f9ec933c4979ef6fae5635a941c83ef5ec78387. @kadyb please add a link there.

**Comment by kadyb** [comment]
@Nowosad what do you think of the minimum R version set to 3.5? Maybe this is too high a requirement and we should support older R versions? The only change is setting _version 2_ in the `save` function when saving the data file.

**Comment by Nowosad** [comment]
I do not have a strong opinion here. On the one hand, 3.5 is about two years old and I encourage everyone to regularly update their R versions. On the other hand, saving using version 2 is very easy to do. Decision is yours.

**Comment by kadyb** [comment]
@Nowosad I fixed all these problems. Now, there is only one note on RCMDCHECK about a new maintainer on CRAN.

**Comment by kadyb** [comment]
@Nowosad There is a new [note](https://github.com/kadyb/rgugik/runs/971202503?check_suite_focus=true) after create "vignette" folder (we should probably add this to ".Rbuildignore"?):

>   Non-standard file/directory found at top level:
>     ‘vignette’

**Comment by Nowosad** [comment]
I think I fixed that a few days ago.

**Comment by kadyb** [comment]
I think it should be open until we release the package on CRAN. We still have one issue (probably the biggest).

**Comment by Nowosad** [comment]
True, but this issue is also mentioned in https://github.com/kadyb/rgugik/issues/2. (I closed this one to remove duplicates).

**Comment by kadyb** [comment]
OK, let's keep this issue open (I removed duplicate in #2).

**Comment by kadyb** [comment]
`http_error` from **httr** package probably will be the easiest solution.

**Comment by Nowosad** [comment]
There are still some issues with failing gracefully. There are some issues with the opendata.geoportal.gov.pl portal in the last two days. It sometimes works and sometimes does not. However, when the file download does not work, then **rgugik** either returns strange errors or downloads files of size about ~200kB.

**Comment by Nowosad** [comment]
Btw - maybe we can learn something from https://books.ropensci.org/http-testing/graceful-http-r-packages.html.

**Comment by kadyb** [comment]
```
-- ERROR (test-topodb_download.R:2:1): (code run outside of `test_that()`) -----
Error: incorrect county name
Backtrace:
    x
 1. \-rgugik::topodb_download(...) test-topodb_download.R:2:0
```

```
-- ERROR (test-models3D_download.R:2:1): (code run outside of `test_that()`) ---
Error: incorrect county name
Backtrace:
    x
 1. \-rgugik::models3D_download(...) test-models3D_download.R:2:0
```

In both cases the input name is "Świętochłowice", so there is probably an encoding problem here. Tests locally and on GitHub work fine. Can we do something about it or should we change the input name?

**Comment by kadyb** [comment]
From CRAN:
```
   Found the following (possibly) invalid URLs:
     URL: File:DTM
       From: inst/doc/DEM.html
       Message: Invalid URI scheme
     URL: https://kadyb.github.io/rgugik (moved to
https://kadyb.github.io/rgugik/)
       From: DESCRIPTION
             man/rgugik-package.Rd
       Status: 200
       Message: OK
     URL: https://www.qgis.org (moved to https://www.qgis.org/en/site/)
       From: README.md
       Status: 200
       Message: OK

Please change http --> https, add trailing slashes, or follow moved
content as appropriate.
```

**Comment by Nowosad** [comment]
@kadyb The first one was not a false positive. Paste the https://kadyb.github.io/rgugik url in the browser and you will see that it changes to https://kadyb.github.io/rgugik/.

**Comment by kadyb** [comment]
Yeah, I fixed it. I meant it:

```
     URL: File:DTM
       From: inst/doc/DEM.html
       Message: Invalid URI schem
```

**Comment by kadyb** [comment]
I'm wrong. This above is also true positive. In generated DEM vignette there is `“File:DTM DSM.svg,”`, so this is incorrect.

**Comment by Nowosad** [comment]
> ```
> -- ERROR (test-topodb_download.R:2:1): (code run outside of `test_that()`) -----
> Error: incorrect county name
> Backtrace:
>     x
>  1. \-rgugik::topodb_download(...) test-topodb_download.R:2:0
> ```
> 
> ```
> -- ERROR (test-models3D_download.R:2:1): (code run outside of `test_that()`) ---
> Error: incorrect county name
> Backtrace:
>     x
>  1. \-rgugik::models3D_download(...) test-models3D_download.R:2:0
> ```
> 
> In both cases the input name is "Świętochłowice", so there is probably an encoding problem here. Tests locally and on GitHub work fine. Can we do something about it or should we change the input name?
> 
> Edit: [Encoding issues](https://cran.csiro.au/doc/manuals/r-patched/R-exts.html#Encoding-issues), so maybe it just changes names.

@kadyb have you tried anything to fix this issue?
I have some ideas - starting from (a) not using this type of input names in tests (maybe the encoding issue is only related to the testing files) to (b) removing polish letters from characters (e.g., "Swietochlowice" instead of "Świętochłowice")...

**Comment by kadyb** [comment]
This is fixed in c8c453b.
However, I have MANY character encoding problems trying to get into CRAN. Probably this is because on Windows 8 I can't save R files with UTF-8 encoding and cp-1250 is not supported on CRAN. I can see there are even problems with the DESCRIPTION file.

The first idea is better and I did it in mentioned commit, but we still have Polish names in DESCRIPTION, README, examples and docs. I don't know if some names should not be written in the "\ uxxxx" notation.

That's why I asked you to build the package on Linux, but I don't know if that's enough.

**Comment by kadyb** [comment]
```
1. Please always write package names, software names and API (application
    programming interface) names in single quotes in title and description.
    e.g: GUGiK --> 'GUGiK'
    Please note that package names are case sensitive.

2. Please only capitalize sentence beginnings and names in the description
    text.
    e.g.:
    Digital Elevation Models --> digital elevation models
    State Register of Borders --> state register of borders

3. Please add () behind all function names in the description texts
    (DESCRIPTION file). e.g: --> geocodePL_get()
    Please do not write function names in quotes.

4. Please always explain all acronyms in the description text. e.g. DTM, DSM

5. Please always make sure to reset to user's options(), working directory
    or par() after you changed it in examples and vignettes and demos.
    e.g.:
    oldwd <- getwd()
    ...
    setwd(...)
    ...
    setwd(oldwd)
```

**Comment by kadyb** [comment]
Ad 5. Is it not related? I don't remember using `options()`, `setwd()` or `par()` anywhere.

**Comment by Nowosad** [comment]
AD5 - maybe this is it - https://github.com/kadyb/rgugik/blob/855edb94fdb8edf42ada40263925510a071b19db/vignettes/PRECOMPILE.R?

**Comment by kadyb** [comment]
Hard to say. I guess user can't use this?

**Comment by Nowosad** [comment]
Yep, but maybe this code was visible for CRAN check. Just add 

```
    oldwd <- getwd()
    ...
    setwd(...)
    ...
    setwd(oldwd)

```

**Comment by kadyb** [comment]
Please check the changes, generate a new source build and send e-mail to me.

**Comment by Nowosad** [comment]
Done

**Comment by kadyb** [comment]
```
package rgugik_0.2.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:

* checking package dependencies ... ERROR
Package required but not available: 'sf'
```

Wait 1 hour and submit again?

**Comment by Nowosad** [comment]
No idea - I have not seen this error yet...

**Comment by kadyb** [comment]
I get this e-mail (I didn't resubmit yet):

`We will trigger new checks.`

so I understand it to wait and not submit again.

**Comment by kadyb** [comment]
rgugik is now officially on CRAN: https://cran.r-project.org/web/packages/rgugik/index.html
