### ISSUE TITLE
GDAL error: unit of measure not found

### ISSUE THREAD

**Issue by mikerspencer** [kadyb/rgugik#70]
Ortho vignette (https://github.com/kadyb/rgugik/blob/master/vignettes/orthophotomap.Rmd), line 236/7.

    Warning message:
    In CPL_read_gdal(as.character(x), as.character(options), as.character(driver),  :
      GDAL Error 1: PROJ: proj_uom_get_info_from_database: unit of measure not found

My gdal version (3.2.1 on Ubuntu 20.04).

The following line (247) generates 38 gdal warnings:

    38: In CPL_read_gdal(as.character(x), as.character(options),  ... :
    GDAL Message 1: for band 3, nodata value has been clamped to 0,
      the original value being out of range.

The same out of range error appears from line 260 and 271, but the plots are created.

Submitted as part of JOSS review: https://github.com/openjournals/joss-reviews/issues/2948

**Comment by kadyb** [comment]
Which version of `sf` and `stars` are you using?

How do you use these vignettes? From [website](https://kadyb.github.io/rgugik/articles/) and rewrite the code to R? Or do you run Rmarkdown from [vignettes catalog](https://github.com/kadyb/rgugik/tree/master/vignettes)?

**Comment by kadyb** [comment]
I tried to reproduce this with `GEOS 3.8.0, GDAL 3.0.4, PROJ 6.3.1, sf 0.9.7, stars 0.5.2` on Windows 8.1 and Pop!_OS 20.04 LTS. This warning and GDAL message didn't show up for me, so it may be only related to the logging options.

It seems to me that there is nothing to worry about. The warning is related to the lack of specification of the coordinate system in the raster. We use `st_crs(img) = 2180` in next steps to fix it. The GDAL message also seems to be related to data, so I think it can be skipped.

**Comment by mikerspencer** [comment]
sf version 0.9-7
stars version 0.4-3

I agree it's not a worry - everything worked subsequently and was plotted in the right place.

**Comment by kadyb** [comment]
Right. I can also recommend upgrading `stars` to the new version because it is a really great package, but I don't know if it will affect the printing of warnings/messages from GDAL. Anyway, thanks for reporting!
