### ISSUE TITLE
Can't load data inside "models3D_download" fun

### ISSUE THREAD

**Issue by kadyb** [kadyb/rgugik#8]
```r
library("rgugik")
models3D_download(county = "Toruń")
#> Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
#> In addition: Warning message:
#> In readChar(con, 5L, useBytes = TRUE) :
#>  cannot open compressed file 'data/TERYT_county.rda', probable reason 'No such file or directory'
```

in line: `load("data/TERYT_county.rda")`

**Comment by Nowosad** [comment]
You should not (probably even cannot) use `load` inside of the function.
The `TERYT_country` should be available inside of the functions without using `load()`.

**Comment by Nowosad** [comment]
I removed it in the recent commit.

**Comment by kadyb** [comment]
Now we have `rgugik::TERYT_county` to read internal data.
