### ISSUE TITLE
Connection Error - ortho_request DEM_request

### ISSUE THREAD

**Issue by jozphlp** [kadyb/rgugik#80]
When I run either ortho_request(x) or DEM_request(x), it shows a "connection error". Nothing on the package documentation suggests that I need some kind of authentication. Is there something I am missing?
![Screenshot from 2021-05-05 11-27-44](https://user-images.githubusercontent.com/79854603/117128200-ff01b880-ad94-11eb-9b50-a6ccce1378da.png)

**Comment by kadyb** [comment]
No, authentication is not required. I suspect that if you are not connecting from Poland, maybe your IP is banned to protect against spam/DoS attacks.

You can check if sending requests works in your web browser. Here is an example URL from `DEM_request()`:

```
https://mapy.geoportal.gov.pl/gprest/services/SkorowidzeFOTOMF/MapServer/1/query?geometry={'xmin':360207.759479622, 'ymin':512866.601609941, 'xmax':360298.871256537, 'ymax':512957.713386855, 'spatialReference':{'wkid':2180}}&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&outFields=godlo,akt_rok,format,charPrzest,bladSrWys,ukladXY,ukladH,czy_ark_wypelniony,url_do_pobrania,nazwa_pliku,idSerie,sha1,asortyment&returnGeometry=false&f=json
```

**Comment by jozphlp** [comment]
Thanks for your reply. I tried the sending request through web, and it worked fine. 

As my IP appears to be banned, could you please  point me to resources on how to use browser requests to accomplish the same?

Thanks very much in advance

**Comment by kadyb** [comment]
Oh, that's weird. I expected that it wouldn't work in the web browser either. So it is somehow related to the package.

Generally, spatial data for Poland can be downloaded from [Geoportal](https://mapy.geoportal.gov.pl/).
![Geoportal](https://user-images.githubusercontent.com/35004826/117156703-42245180-adbe-11eb-832b-c336b7f94aca.png)

The second way, recently added, is to use Web Coverage Services in e.g. QGIS. The disadvantage is that the number of datasets and the data types are limited compared to this package. There is link with information: https://www.geoportal.gov.pl/uslugi/usluga-sieciowa-wcs

**Comment by kadyb** [comment]
Could you test the code below to see what error it returns? 

```r
req = "https://mapy.geoportal.gov.pl/gprest/services/SkorowidzeFOTOMF/MapServer/1/query?geometry={'xmin':360207.759479622, 'ymin':512866.601609941, 'xmax':360298.871256537, 'ymax':512957.713386855, 'spatialReference':{'wkid':2180}}&geometryType=esriGeometryEnvelope&spatialRel=esriSpatialRelIntersects&outFields=godlo,akt_rok,format,charPrzest,bladSrWys,ukladXY,ukladH,czy_ark_wypelniony,url_do_pobrania,nazwa_pliku,idSerie,sha1,asortyment&returnGeometry=false&f=json"
output = jsonlite::fromJSON(req)
```

**Comment by jozphlp** [comment]
The request run without error 
![Screenshot_2021-05-05 https mapy geoportal gov pl](https://user-images.githubusercontent.com/79854603/117165778-b4486680-adbd-11eb-99bb-7685db06364d.png)

**Comment by kadyb** [comment]
I mean, run the above code in R :)

**Comment by jozphlp** [comment]
It worked without any error. 
![Screenshot from 2021-05-05 16-26-52](https://user-images.githubusercontent.com/79854603/117167041-d2629680-adbe-11eb-967d-532d03549da5.png)

**Comment by jozphlp** [comment]
I figured out where I went wrong. I did not have "stars" in my system. It's working fine now through R code. Thanks very much for the help
