### ISSUE TITLE
More informational errors on failure 

### ISSUE THREAD

**Issue by kadyb** [kadyb/rgugik#81]
The error returned on failure should be more informative. Currently, when an error with data access occurs, `conection error` is returned. However, it does not have to be related to a connection problem at all (see #80).

I think it would be best to capture the error from an internal function and return it as text to satisfy CRAN requirements.

**Comment by kadyb** [comment]
@Nowosad, should be better now. Please test if it is OK in real use cases.

**Comment by Nowosad** [comment]
I tested some of my cases -- works fine. I will reopen this issue if I will find anything.
