### ISSUE TITLE
get lidar for whole of Poland

### ISSUE THREAD

**Issue by jozphlp** [kadyb/rgugik#82]
Hi there,

Is there an efficient way to download dtm data for the entire country ?

Thanks very much

**Comment by kadyb** [comment]
I think not. Downloading data for the entire country will not be trivial. As far as I know, it will be over 2 TB of data.

You should divide the country into blocks as only 1000 tiles can be returned in one query. Next, you should write your own function to download the files and handle errors and retries. Also, remember to filter the metadata, so you don't download every possible dataset.

Here is a download service (Web Coverage Service) where you can define your own spatial extents in QGIS, but it only applies to raster data: https://www.geoportal.gov.pl/uslugi/usluga-sieciowa-wcs (click on the UK flag icon in the top right corner to change the language to English).
