### ISSUE TITLE
geodb_download error

### ISSUE THREAD

**Issue by Nowosad** [kadyb/rgugik#87]
``` r
library(rgugik)
geodb_download("wielkopolskie", outdir = "./data")
#> Warning in utils::download.file(df_names[i, "URL"], filename, mode = "wb", :
#> cannot open URL 'https://opendata.geoportal.gov.pl/bdoo/PL.PZGiK.201.30.zip':
#> HTTP status was '404 Not Found'
```

Also, when I try to open the link using my browser, I got -- `plik nie istnieje: /bdoo/PL.PZGiK.201.30.zip`.

**Comment by Nowosad** [comment]
Maybe it has something in common with:

![image](https://user-images.githubusercontent.com/3457131/150115192-b105003f-61c2-4938-8754-38bc5392306f.png)

**Comment by kadyb** [comment]
The servers had maintenance. Now it's working.
