### ISSUE TITLE
Polish borders - idea

### ISSUE THREAD

**Issue by Nowosad** [kadyb/rgugik#88]
Hi @kadyb -- quick question/idea -- would it be possible to return Polish borders by default using the `borders_get()` function? 

If not -- feel free to close the issue (and I will use `borders_download()` for my project).

**Comment by kadyb** [comment]
It is possible, but this function needs to be rewritten.

Currently, you can use this instead of `borders_download()`:

```r
library("rgugik")
poland = borders_get(voivodeship = voivodeship_names[, 1])
poland = sf::st_union(poland, is_coverage = TRUE)
plot(poland)
```

**Comment by Nowosad** [comment]
Cool idea. How about applying some recursion here -- https://github.com/kadyb/rgugik/pull/89?

**Comment by kadyb** [comment]
Thanks! However, the readability of this function is terrible.
