### ISSUE TITLE
Nie widzi najnowszych danych orto i lidar

### ISSUE THREAD

**Issue by bodrgit** [kadyb/rgugik#93]
Nie widzi najnowszych danych orto i lidar /z 2022r/.

**Comment by kadyb** [comment]
Dzięki. Wygląda na to, że dane z 2022 r. są dostępne na Geoportalu, ale nie zostały dodane do usługi wyszukiwania. Napiszę do GUGiK.

**Comment by bodrgit** [comment]
Czy jest szansa na szybkie rozwiązanie tego problemu?.

**Comment by kadyb** [comment]
Ciężko mi powiedzieć. Nie otrzymałem jeszcze odpowiedzi od GUGiKu, ale widzę, że wystawili nową usługę do wyszukiwania danych, która różni się od poprzedniej. Zatem pojawiają się pytania (na które aktualnie nie znam odpowiedzi):

1. Czy nowa usługa będzie docelową (tj. stara przestanie istnieć) czy będą obie istnieć równolegle, ale nowe dane będą dostępne jedynie w nowej wersji?
2. Na czym dokładnie polegają różnice między wersjami?

W przyszłym tygodniu jeszcze raz napiszę do GUGiKu i spróbuję usiąść do tego problemu.

**Comment by kadyb** [comment]
Rozdzielczość nowych danych (5 cm) jest całkiem niezła. Można zauważyć studentów podczas praktyk z geodezji 😃 

![studenci](https://user-images.githubusercontent.com/35004826/219359167-49444ff6-e53d-455b-872c-962474bc075f.png)

**Comment by bodrgit** [comment]
Teraz działa jak należy. Dzięki za szybkie zadziałanie bo nowych danych coraz więcej.

**Comment by kadyb** [comment]
Nowa wersja pakietu jest już na CRAN. Instalacja: `install.packages("rgugik")`.
