### ISSUE TITLE
Othophotomap download problem

### ISSUE THREAD

**Issue by uzawadzka** [kadyb/rgugik#96]
I have problem with tile_download() function. Below I paste the code chunk and error message that I get:
library(sf)
library(rgugik)
options(timeout = 10000)
polygon_path = system.file("datasets/search_area.gpkg", package = "rgugik")
polygon = read_sf(polygon_path)

req_df = ortho_request(polygon)
tile_download(req_df[1, ]) # download the first image only
req_df = DEM_request(polygon)
tile_download(req_df[1, ]) # download the first DEM only
> tile_download(req_df[1, ]) # download the first DEM only
1/1
the 'wininet' method is deprecated for http:// and https:// URLs
Conection error.
If the problem persists, try a different download method from 'download.file()' and/or increase timeout 'options(timeout = 600)'.

My configuration is Windows 10, R - version 4.2.3 (2023-03-15 ucrt) -- "Shortstop Beagle", Rstudio - Version 1.1.383.

**Comment by kadyb** [comment]
The problem is with: `the 'wininet' method is deprecated for http:// and https:// URLs` on Windows. You should change the download method in `tile_download()` to something else, like this:

```r
tile_download(req_df[1, ], method = "libcurl")
tile_download(req_df[1, ], method = "curl")
```

You can also use `wget` on Windows, but before that you have to download it as an external tool, but I didn't tested it.

**Comment by uzawadzka** [comment]
Thanks, it works.

śr., 29 mar 2023 o 13:00 Krzysztof Dyba ***@***.***>
napisał(a):

**Comment by Nowosad** [comment]
@kadyb could we add a code to check if the method is `wininet` and then try to replace it with, e.g., `"libcurl"`?

**Comment by kadyb** [comment]
Maybe the problem is with old version of RStudio (from 2017) that overwrites the default download method? But I'm guessing.
