### ISSUE TITLE
Incorrect TERYT codes from the `commune_names` variable

### ISSUE THREAD

**Issue by wacekk** [kadyb/rgugik#97]
First of all, I would like to thank you very much for all the work you put into developing the rgugik package, which I often use.

I noticed that in the rgugik package, the `commune_names` variable has outdated TERYT commune codes. I am using version 0.4.0. package (from CRAN).

I joined data from `commune_names` with this data: https://www.gov.pl/web/mswia/baza-jst and in 35 cases (for communes), the join failed. I present filtered data with errors below:
```
"TERYT";"NAME";"Kod_TERYT"
"2416092";"Włodowice";"2416093"
"1010082";"Rozprza";"1010083"
"0602062";"Goraj";"0602063"
"3019032";"Kaczory";"3019033"
"1419022";"Bodzanów";"1419023"
"2606022";"Iwaniska";"2606023"
"2404122";"Olsztyn";"2404123"
"1425062";"Jedlnia-Letnisko";"1425063"
"1002032";"Dąbrowice";"1002033"
"1434062";"Jadów";"1434063"
"0414082";"Pruszcz";"0414083"
"3007052";"Koźminek";"3007053"
"1412102";"Latowicz";"1412103"
"1409062";"Solec nad Wisłą";"1409063"
"1211032";"Czarny Dunajec";"1211033"
"1015012";"Bolimów";"1015013"
"1021042";"Jeżów";"1021043"
"0608052";"Kamionka";"0608053"
"1813022";"Dubiecko";"1813023"
"0218032";"Miękinia";"0218033"
"3019052";"Miasteczko Krajeńskie";"3019053"
"1208042";"Książ Wielki";"1208043"
"2604082";"Łopuszno";"2604083"
"1420082";"Nowe Miasto";"1420083"
"1016102";"Ujazd";"1016103"
"1438052";"Wiskitki";"1438053"
"1420112";"Sochocin";"1420113"
"0606042";"Izbica";"0606043"
"1430022";"Jastrząb";"1430023"
"1412042";"Cegłów";"1412043"
"1008062";"Lutomiersk";"1008063"
"2602092";"Wodzisław";"2602093"
"2604142";"Piekoszów";"2604143"
"3001022";"Budzyń";"3001023"
"0224032";"Kamieniec Ząbkowicki";"0224033"
```

 The `Kod_TERYT` column is data from the MSWiA file; the `TERYT` column is data from the `commune_names` variable. According to my cursory analysis, these communes have changed their status from rural (wiejska) to urban-rural (miejsko-wiejska) or urban (miejska). I wrote a function to replace the wrong TERYT, but please consider the problem in your free time and update the package with the current, official data from Statistics Poland (Główny Urząd Statystyczny).

The `borders_get` function works fine, regardless of the last digits of the TERYT code.

**Comment by kadyb** [comment]
Thank you very much. I updated this file in the dev version of the package.
